---
title: "Equations for AJB-00205"
output: word_document
date: "2022-10-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Mertensia fusiformis: 100 individuals, 4 sites

Delphinium nuttallianum: 84 individuals, 4 sites

Potentilla pulcherrima: 67 individuals, 7 sites


*5 fixed effects:*

- "flowers" number of flowers on the plant

- "deviation" number of days an individuals blooming peak is from the population peak

- "early/late" before or after the population peak bloom

- "conspecifics" number of conspecific plants blooming at the same time

- "treatment" plot treatment, either accelerated snowmelt or natural


*2 response variables:*

- "dev.seed" number of developed seeds

- "cbind(dev.seed,undev.seeds)" proportion of developed seeds to undeveloped seeds


## Distributions used:

Mertensia, Delphinium, and Potentilla developed seed counts: negative binomial

Mertensia proportion of developed seeds: binomial

Delphinium proportion of developed seeds: betabinomial


## R models look like this: 

mert.glmmtmb<-glmmTMB(dev.seed ~ flowers:(deviation*early.late) + flowers:number.conspecifics/plot.treat  + (1|site), ziformula=~1, family = "nbinom2", data = mert.open)

Mert.prop.glmmtmb<-glmmTMB(cbind(dev.seed,undev.seeds) ~ flowers:(deviation * early.late) + flowers:number.conspecifics/plot.treat + (1|site), family = binomial, data = mert.open) 

## Mathematical notation

### Terms

$\beta_0$ is the intercept

$\beta$ is regression coefficient for fixed effects

F = flowers

D = deviation

E = early/late

C = conspecifics

T = treatment

z = site (as random effect)

u = random effect regression coefficients


### Mertensia count model:

PMF for negative binomial, with linear model as x

y = $r + M - 1 \choose M$ $p^r (1-p)^ M + \epsilon$

linear model

M = $\beta_0 + \beta_1 F_i D_i + \beta_2 F_i E_i + \beta_3 F_i E_i D_i + \beta_4 F_i C_i + \beta_5 F_i C_i T_i + z_i u$


### Mertensia proportion model:

PMF for binomial, with linear model as x

y = $n \choose M$ $p^M (1-p)^{n-M} + \epsilon$

linear model

M = $\beta_0 + \beta_1 F_i D_i + \beta_2 F_i E_i + \beta_3 F_i E_i D_i + \beta_4 F_i C_i + \beta_5 F_i C_i T_i + z_i u$

### Delphinium proportion model:

PMF for betabinomial, with linear model as x

y = $\frac {B(D + \alpha(n) - D + \beta)} {B(\alpha,\beta)}$ + $\epsilon$

linear model

D = $\beta_0 + \beta_1 F_i D_i + \beta_2 F_i E_i + \beta_3 F_i E_i D_i + \beta_4 F_i C_i + \beta_5 F_i C_i T_i + z_i u$





