---
title: "Mixed Effects Models"
author: "Annie Schiffer"
date: "1/21/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Delphinium

```{r Delphinium mixed effects model}
#install.packages("lme4")
library(lme4) #loading package for mixed effects model 
delph = read.csv("~/Documents/BROSI/THESIS/Data Cleaning/Delphinium_final2.csv") #loading Delphinium data
Delph.glmer = glmer(total.seeds ~ relative.position + plot.treat + (1|site), family = poisson,  data = delph, na.action = na.omit) # model
summary(Delph.glmer) #model output
```

##Mertensia

```{r Mertensia mixed effects model}
mert = read.csv("~/Documents/BROSI/THESIS/Data Cleaning/Mertensia_final2.csv") #loading Mertensia data
Mert.glmer = glmer(total.seeds ~ relative.position + plot.treat + (1|site), family = poisson, data = mert, na.action = na.omit)
summary(Mert.glmer)
```

##Potentilla

```{r Potentilla mixed effects model}
pot = read.csv("~/Documents/BROSI/THESIS/Data Cleaning/Potentilla_final2.csv") # loading Potentilla data
Pot.glmer = glmer(total.seeds ~ relative.position + plot.treat + (1|site), family = poisson, data = pot, na.action = na.omit)
summary(Pot.glmer)
```

testing Git Hub